[tool.poetry]
name = "dmso-solubility"
version = "0.1.0"
description = ""
authors = ["MMANNING <manning.matthew@epa.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
